Code.require_file "../sql/alter_table.exs", __DIR__
Code.require_file "../sql/lock.exs", __DIR__
Code.require_file "../sql/migration.exs", __DIR__
Code.require_file "../sql/escape.exs", __DIR__
Code.require_file "../sql/transaction.exs", __DIR__
Code.require_file "../cases/joins.exs", __DIR__
Code.require_file "../cases/repo.exs", __DIR__
Code.require_file "../cases/type.exs", __DIR__
Code.require_file "../cases/preload.exs", __DIR__
